stages:
  - build

.release_only_template: &release_only
  only:
    - tags
    - /^[\d-]+-release$/

.exclude_release_template: &exclude_release
  except:
    - tags
    - /^[\d-]+-release$/

.build_all_template: &build_all
  stage: build
  script:
    - tup init
    - tup variant configs/*
    - tup
  artifacts:
    expire_in: 1 week
    paths:
      - build-*/src/hypervisor-x86_64

build:default-fedora:
  image: fedora:latest
  before_script:
    - dnf -y update && dnf -y install 'dnf-command(copr)' && dnf -y copr enable boelthorn/tup
    - dnf -y update && dnf -y install gcc gcc-c++ tup
  <<: *build_all
  <<: *exclude_release

.build_ubuntu_template: &build_ubuntu
  image: ubuntu:bionic
  before_script:
    - apt-get update && apt-get -y install software-properties-common && add-apt-repository -y ppa:js-alien8/tup
    - apt-get update && apt-get -y install build-essential tup g++

build:default-ubuntu:
  <<: *build_ubuntu
  <<: *build_all

build:release:
  <<: *build_ubuntu
  stage: build
  script:
    - tup init
    - tup variant configs/default.config
    - tup
  artifacts:
    expire_in: 5 year
    paths:
      - build-*/src/hypervisor-x86_64
