stages:
  - build
  - deploy

.build_template: &build_options
  stage: build
  image: gcc:7
  script:
  - gcc --version
  - cd build && make ARCH=$ARCH
  artifacts:
    paths:
      - build/hypervisor-$ARCH

.release_only_template: &release_only
  only:
    - tags
    - /^[\d-]+-release

build:x86_64:
  variables:
    ARCH: x86_64
  artifacts:
    expire_in: 1 week
  <<: *build_options

build:release:
  variables:
    ARCH: x86_64
  <<: *build_options
  <<: *release_only

artifacts:
  stage: deploy
  image: ubuntu:latest
  tags:
    - artifacts
  variables:
    CI_ARTIFACT_PATH: /srv/html/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG
  dependencies:
    - build:x86_64
  script:
    - mkdir -p /$CI_ARTIFACT_PATH
    - cp build/hypervisor-x86_64 $CI_ARTIFACT_PATH/nova

